name: Github Actions CI

on:
  push:
    branches:
      - master
  pull_request: 
    branches:
      - master
  schedule:
    - cron: "0 5 * * 0"

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run brew test-bot
      run: |
        set -e
        brew update
        brew cleanup
        HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/sashkab/homebrew-python"
        mkdir -p "$HOMEBREW_TAP_DIR"
        rm -rf "$HOMEBREW_TAP_DIR"
        ln -s "$PWD" "$HOMEBREW_TAP_DIR"
        brew test-bot
        
